#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NotiXamarin.Resource", IsApplication=true)]

namespace NotiXamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int listitemselected = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int listitemunselected = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int read_later = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int read_later_white = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int action_read_later = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int delete_saved_news = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int newsBody = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int newsImage = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int newsListFragmentContainer = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int newsListRow_RelativeLayout = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int newsListView = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int newsTitle = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int NewsList = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int NewsListFragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int NewsListRow = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int newsActionMenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int savedNewsActionMenu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int NewsListActivity_Tabs_AllNews_Header = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int NewsListActivity_Tabs_SavedNews_Header = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
